In [14]:
import scipy.sparse as sparse
import numpy as np

In [61]:

JX_ON = True
JU_ON = True
JDU_ON = True
SOFT_ON = True



## compute the matrices required for Quadratic Program

In [ ]:
def compute_QP_matrices():
    Np = 5
    Nc = 5 
    nx = 4
    nu = 1
    eps_feas=1e6
    Qx = sparse.diags([10., 5., 100., 5.])
    QxN = Qx.copy()
    Qu = sparse.diags([0.1]) 
    QDu = np.zeros((nu,nu))
    xref = np.array([0., 0., 0., 0.])
    uref = np.zeros(nu)
    uminus1 = uref
    Qeps = eps_feas * sparse.eye(nx)
    # Ad = Ad
    # Bd = Bd
    # x0 = x0
    # xmin = xmin
    # xmax = xmax
    # umin = umin
    # umax = umax
    # Dumin = Dumin
    # Dumax = Dumax
    # Qeps = Qeps

    # casting the MPC problem to a Quadratic Program 
    P_X = sparse.csc_matrix(((Np+1)*nx, (Np+1)*nx))
    q_X = np.zeros((Np+1)*nx)  # x_N
    J_CNST = 0.0
    # for penalizing the states
    if JX_ON:
        P_X += sparse.block_diag([sparse.kron(sparse.eye(Np), Qx),QxN])   # quadratic part 
        q_X += np.hstack([np.kron(np.ones(Np), -Qx.dot(xref)),-QxN.dot(xref)])  # linear part
    else:
        pass
    # for penalizing the control inputs
    P_U = sparse.csc_matrix((Nc*nu, Nc*nu))
    q_U = np.zeros(Nc*nu)
    if JU_ON:
        J_CNST += 1/2*Np*(uref.dot(Qu.dot(uref)))
        if Nc == Np:
            P_U += sparse.kron(sparse.eye(Nc), Qu)
            q_U += np.kron(np.ones(Nc), -Qu.dot(uref))
    else:
        pass
    # for penalizing change in control inputs
    if JDU_ON:
            J_CNST += 1/2*uminus1.dot((QDu).dot(uminus1))
            iDu = 2 * np.eye(Nc) - np.eye(Nc, k=1) - np.eye(Nc, k=-1)
            iDu[Nc - 1, Nc - 1] = 1
            P_U += sparse.kron(iDu, QDu)
            q_U += np.hstack([-QDu.dot(uminus1),np.zeros((Nc - 1) * nu)]) 
    else:
        pass 
    # introducing soft constraints 
    if SOFT_ON:
            P_eps = sparse.kron(np.eye((Np+1)), Qeps)
            q_eps = np.zeros((Np+1)*nx)


    # linear dynamics x_k+1 = Ax_k + Bu_k
    Ax = sparse.kron(sparse.eye(Np + 1), -sparse.eye(nx)) + sparse.kron(sparse.eye(Np + 1, k=-1), Ad)







    
    


        





In [63]:
compute_QP_matrices()

In [32]:
np.ones(Np)

array([1., 1., 1., 1., 1.])

In [31]:
Np = 5
Nc = 5 
nx = 4
nu = 1
Qx = sparse.diags([10., 5., 100., 5.])
QxN = Qx.copy()
Qu = sparse.diags([0.1]) 
# QDu = QDu
xref = np.array([0., 0., 0., 0.])
-Qx.dot(xref)

array([-0., -0., -0., -0.])

In [33]:
np.kron(np.ones(Np), -Qx.dot(xref))

array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0.])